######################################################################################################

import pandas as pd
import numpy as np

######################################################################################################

def bond_cash_flows(maturity, principal, coupon_rate, coupons_per_year):
    """

    Returns the series of cash flows generated by a bond:

    1- Cash flows indexed by the payment/coupon number.
        
    """
    n_coupons = round(maturity * coupons_per_year)
    coupon_amount = principal * coupon_rate / coupons_per_year
    coupons = np.repeat(coupon_amount, n_coupons)
    coupon_times = np.arange(1, n_coupons + 1)
    cash_flows = pd.Series(data = coupon_amount, index = coupon_times)
    cash_flows.iloc[-1] += principal
    return cash_flows